---
- name: "REVERSEPROXY - Ensure that directory are created"
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    state: directory
  loop: "{{ reverseproxy_dirs }}"

- name: "REVERSEPROXY - Copy files"
  copy:
    src: "{{ item.src }}"
    dest: "{{ reverseproxy_path }}/{{ item.dest | default(item.src) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ reverseproxy_files }}"
  notify: "docker reverseproxy restart"

- name: "REVERSEPROXY - Create files from template"
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ reverseproxy_path }}/{{ item.dest | default(item.src) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ reverseproxy_templates }}"
  notify: "docker reverseproxy restart"

- name: "REVERSEPROXY - Install docker images"
  docker_image:
    name: "{{ docker_images.nginx }}"
    force_tag: yes
    source: pull
  notify: "docker reverseproxy restart"

- name: "REVERSEPROXY - Create docker-compose.yml from template"
  template:
    src: "reverseproxy/docker-compose.yml.j2"
    dest: "{{ reverseproxy_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  notify: "docker reverseproxy restart"


- name: "REVERSEPROXY - Start docker image"
  community.docker.docker_compose:
    project_src: "{{ reverseproxy_path }}"
    state: present

- name: "REVERSEPROXY - site-specific tasks"
  when: reverseproxy_site_specific_tasks is defined
  include_tasks:
    file: "files/{{ reverseproxy_site_specific_tasks }}"
    apply:
      tags:
        - site_specific
  tags:
    - site_specific