---
# handlers file for cesnet.reverseproxy

- name: "REVERSEPROXY - Restart"
  community.docker.docker_compose_v2:
    project_src: "{{ reverseproxy_path }}"
    state: restarted
  listen: "docker reverseproxy restart"